/*
	AUTOGENERATED CODE
	DO NOT EDIT
*/

#include "types.h"

typedef struct {
	f32 *data;
	u64 len, cap;
} f32Array;

f32Array f32ArrayNew(u64 cap) {
	return (f32Array){
		.data = malloc(sizeof(f32) * cap),
		.len = 0,
		.cap = cap
	};
}

void f32ArrayPush(f32Array* array, f32 val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

f32 f32ArrayPop(f32Array* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

f32 f32ArrayLast(f32Array array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

f32* f32ArrayLastMut(f32Array array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

f32 f32ArrayGet(f32Array array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

f32* f32ArrayGetMut(f32Array array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "types.h"

typedef struct {
	i32 *data;
	u64 len, cap;
} i32Array;

i32Array i32ArrayNew(u64 cap) {
	return (i32Array){
		.data = malloc(sizeof(i32) * cap),
		.len = 0,
		.cap = cap
	};
}

void i32ArrayPush(i32Array* array, i32 val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

i32 i32ArrayPop(i32Array* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

i32 i32ArrayLast(i32Array array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

i32* i32ArrayLastMut(i32Array array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

i32 i32ArrayGet(i32Array array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

i32* i32ArrayGetMut(i32Array array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "types.h"

typedef struct {
	v2 *data;
	u64 len, cap;
} v2Array;

v2Array v2ArrayNew(u64 cap) {
	return (v2Array){
		.data = malloc(sizeof(v2) * cap),
		.len = 0,
		.cap = cap
	};
}

void v2ArrayPush(v2Array* array, v2 val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

v2 v2ArrayPop(v2Array* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

v2 v2ArrayLast(v2Array array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

v2* v2ArrayLastMut(v2Array array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

v2 v2ArrayGet(v2Array array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

v2* v2ArrayGetMut(v2Array array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "types.h"

typedef struct {
	v3 *data;
	u64 len, cap;
} v3Array;

v3Array v3ArrayNew(u64 cap) {
	return (v3Array){
		.data = malloc(sizeof(v3) * cap),
		.len = 0,
		.cap = cap
	};
}

void v3ArrayPush(v3Array* array, v3 val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

v3 v3ArrayPop(v3Array* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

v3 v3ArrayLast(v3Array array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

v3* v3ArrayLastMut(v3Array array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

v3 v3ArrayGet(v3Array array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

v3* v3ArrayGetMut(v3Array array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "types.h"

typedef struct {
	v4 *data;
	u64 len, cap;
} v4Array;

v4Array v4ArrayNew(u64 cap) {
	return (v4Array){
		.data = malloc(sizeof(v4) * cap),
		.len = 0,
		.cap = cap
	};
}

void v4ArrayPush(v4Array* array, v4 val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

v4 v4ArrayPop(v4Array* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

v4 v4ArrayLast(v4Array array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

v4* v4ArrayLastMut(v4Array array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

v4 v4ArrayGet(v4Array array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

v4* v4ArrayGetMut(v4Array array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "types.h"

typedef struct {
	Color *data;
	u64 len, cap;
} ColorArray;

ColorArray ColorArrayNew(u64 cap) {
	return (ColorArray){
		.data = malloc(sizeof(Color) * cap),
		.len = 0,
		.cap = cap
	};
}

void ColorArrayPush(ColorArray* array, Color val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

Color ColorArrayPop(ColorArray* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

Color ColorArrayLast(ColorArray array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

Color* ColorArrayLastMut(ColorArray array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

Color ColorArrayGet(ColorArray array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

Color* ColorArrayGetMut(ColorArray array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "types.h"

typedef struct {
	u64 *data;
	u64 len, cap;
} u64Array;

u64Array u64ArrayNew(u64 cap) {
	return (u64Array){
		.data = malloc(sizeof(u64) * cap),
		.len = 0,
		.cap = cap
	};
}

void u64ArrayPush(u64Array* array, u64 val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

u64 u64ArrayPop(u64Array* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

u64 u64ArrayLast(u64Array array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

u64* u64ArrayLastMut(u64Array array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

u64 u64ArrayGet(u64Array array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

u64* u64ArrayGetMut(u64Array array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

#include "profiler.h"

typedef struct {
	Block *data;
	u64 len, cap;
} BlockArray;

BlockArray BlockArrayNew(u64 cap) {
	return (BlockArray){
		.data = malloc(sizeof(Block) * cap),
		.len = 0,
		.cap = cap
	};
}

void BlockArrayPush(BlockArray* array, Block val) {
	if (array->len >= array->cap) return;
	array->data[array->len++] = val;
}

Block BlockArrayPop(BlockArray* array) {
	assert(array->len > 0);
	return array->data[--array->len];
}

Block BlockArrayLast(BlockArray array) {
	assert(array.len > 0);
	return array.data[array.len - 1];
}

Block* BlockArrayLastMut(BlockArray array) {
	assert(array.len > 0);
	return &array.data[array.len - 1];
}

Block BlockArrayGet(BlockArray array, u64 id) {
	assert(array.len < id);
	return array.data[id];
}

Block* BlockArrayGetMut(BlockArray array, u64 id) {
	assert(array.len < id);
	return &array.data[id];
}

void StubArrayOp(void* array, ...) {
	printf("[ERROR] Array operator called on non-array type\n");
}

#define ArrayNew(type, cap) type##ArrayNew(cap)

#define Push(array, new) _Generic((array), \
	f32Array: f32ArrayPush, \
	i32Array: i32ArrayPush, \
	v2Array: v2ArrayPush, \
	v3Array: v3ArrayPush, \
	v4Array: v4ArrayPush, \
	ColorArray: ColorArrayPush, \
	u64Array: u64ArrayPush, \
	BlockArray: BlockArrayPush, \
	default: StubArrayOp)(&array, new)

#define Pop(array) _Generic((array), \
	f32Array: f32ArrayPop, \
	i32Array: i32ArrayPop, \
	v2Array: v2ArrayPop, \
	v3Array: v3ArrayPop, \
	v4Array: v4ArrayPop, \
	ColorArray: ColorArrayPop, \
	u64Array: u64ArrayPop, \
	BlockArray: BlockArrayPop, \
	default: StubArrayOp)(&array)

#define Last(array) _Generic((array), \
	f32Array: f32ArrayLast, \
	i32Array: i32ArrayLast, \
	v2Array: v2ArrayLast, \
	v3Array: v3ArrayLast, \
	v4Array: v4ArrayLast, \
	ColorArray: ColorArrayLast, \
	u64Array: u64ArrayLast, \
	BlockArray: BlockArrayLast, \
	default: StubArrayOp)(array)

#define LastMut(array) _Generic((array), \
	f32Array: f32ArrayLastMut, \
	i32Array: i32ArrayLastMut, \
	v2Array: v2ArrayLastMut, \
	v3Array: v3ArrayLastMut, \
	v4Array: v4ArrayLastMut, \
	ColorArray: ColorArrayLastMut, \
	u64Array: u64ArrayLastMut, \
	BlockArray: BlockArrayLastMut, \
	default: StubArrayOp)(array)

#define Get(array, id) _Generic((array), \
	f32Array: f32ArrayGet, \
	i32Array: i32ArrayGet, \
	v2Array: v2ArrayGet, \
	v3Array: v3ArrayGet, \
	v4Array: v4ArrayGet, \
	ColorArray: ColorArrayGet, \
	u64Array: u64ArrayGet, \
	BlockArray: BlockArrayGet, \
	default: StubArrayOp)(array, id)

#define GetMut(array, id) _Generic((array), \
	f32Array: f32ArrayGetMut, \
	i32Array: i32ArrayGetMut, \
	v2Array: v2ArrayGetMut, \
	v3Array: v3ArrayGetMut, \
	v4Array: v4ArrayGetMut, \
	ColorArray: ColorArrayGetMut, \
	u64Array: u64ArrayGetMut, \
	BlockArray: BlockArrayGetMut, \
	default: StubArrayOp)(array, id)

