/*
	AUTOGENERATED CODE
	DO NOT EDIT
*/

#include "types.h"
inline i32 u8Sort(const void* from, const void* to) {
	return ((u8*)(from)) - ((u8*)(to));
}

#include "types.h"
inline i32 u16Sort(const void* from, const void* to) {
	return ((u16*)(from)) - ((u16*)(to));
}

#include "types.h"
inline i32 u32Sort(const void* from, const void* to) {
	return ((u32*)(from)) - ((u32*)(to));
}

#include "types.h"
inline i32 u64Sort(const void* from, const void* to) {
	return ((u64*)(from)) - ((u64*)(to));
}

#include "types.h"
inline i32 i8Sort(const void* from, const void* to) {
	return ((i8*)(from)) - ((i8*)(to));
}

#include "types.h"
inline i32 i16Sort(const void* from, const void* to) {
	return ((i16*)(from)) - ((i16*)(to));
}

#include "types.h"
inline i32 i32Sort(const void* from, const void* to) {
	return ((i32*)(from)) - ((i32*)(to));
}

#include "types.h"
inline i32 i64Sort(const void* from, const void* to) {
	return ((i64*)(from)) - ((i64*)(to));
}

#include "types.h"
inline i32 f32Sort(const void* from, const void* to) {
	return ((f32*)(from)) - ((f32*)(to));
}

#include "types.h"
inline i32 f64Sort(const void* from, const void* to) {
	return ((f64*)(from)) - ((f64*)(to));
}

